name: "Install Playwright"
description: "Install Playwright"
runs:
  using: composite
  steps:
    - name: Cache Playwright
      id: cache-playwright
      uses: actions/cache@v4
      env:
        cache-name: cache-playwright
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-test-${{ env.cache-name }}

    - if: ${{ steps.cache-playwright.outputs.cache-hit != 'true' }}
      name: Install Playwright Browsers
      run: npx playwright install chromium --with-deps
      shell: bash
