name: Accessibility tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install node modules
        uses: ./.github/actions/install-node-modules

      - name: Install Playwright
        uses: ./.github/actions/install-playwright

      - name: Build Storybook
        run: npm run build-storybook --quiet

      - name: Run accessibility tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && npm run test-storybook"
