name: ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install node modules
        uses: ./.github/actions/install-node-modules

      - name: Cache Playwright
        id: cache-playwright
        uses: actions/cache@v4
        env:
          cache-name: cache-playwright
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-test-${{ env.cache-name }}

      - if: ${{ steps.cache-playwright.outputs.cache-hit != 'true' }}
        name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Test
        run: npm test

  accessibility-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install node modules
        uses: ./.github/actions/install-node-modules

      - name: Cache Playwright
        id: cache-playwright
        uses: actions/cache@v4
        env:
          cache-name: cache-playwright
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-test-${{ env.cache-name }}

      - if: ${{ steps.cache-playwright.outputs.cache-hit != 'true' }}
        name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Build Storybook
        run: npm run build-storybook --quiet

      - name: Run accessibility tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && npm run test-storybook"
