name: Caching with npm
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: npm ci

      - name: Cache Playwright
        id: cache-playwright
        uses: actions/cache@v4
        env:
          cache-name: cache-playwright
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-test-${{ env.cache-name }}

      - if: ${{ steps.cache-playwright.outputs.cache-hit != 'true' }}
        name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Test
        run: npm test
