name: Unit tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install node modules
        uses: ./.github/actions/install-node-modules

      - name: Install Playwright
        uses: ./.github/actions/install-playwright

      - name: Test
        run: npm test
